### ISSUE TITLE
Error when importing from sort.sort import * in main.py of the project

### ISSUE THREAD

**Issue by dolfMo** [Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8#1] opened 2023-11-09 04:48 UTC
I'm trying to import the Sort class in my project's main.py file using the import statement from sort.sort import Sort, but I'm encountering an import error.

**Comment by Muhammad-Zeerak-Khan** [comment] 2023-11-09 12:22
As a dependency for this project, a git repository for the sort module is mentioned. You may clone that git repo in your root folder or download the zip file in your root folder.
I am linking the git repo for the sort repository here : 

[Sort Module](https://github.com/abewley/sort)


Let me know, if you are still facing the issue.

**Comment by Muhammad-Zeerak-Khan** [comment] 2023-12-30 16:25
Hope that the issue is resolved. Closing the issue.

**Closed by Muhammad-Zeerak-Khan** 2023-12-30 16:25 UTC
